I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    image Fogpart = SnowBlossom("./images/resources/fog.png", count=75, border=50, xspeed=35, yspeed=0, start=5, fast=false, horizontal=True)
  File "game/script.rpy", line 7, in <module>
    image Fogpart = SnowBlossom("./images/resources/fog.png", count=75, border=50, xspeed=35, yspeed=0, start=5, fast=false, horizontal=True)
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    image Fogpart = SnowBlossom("./images/resources/fog.png", count=75, border=50, xspeed=35, yspeed=0, start=5, fast=false, horizontal=True)
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\ast.py", line 875, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Morgan\Downloads\renpy-6.99.4-sdk\renpy\python.py", line 1472, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    image Fogpart = SnowBlossom("./images/resources/fog.png", count=75, border=50, xspeed=35, yspeed=0, start=5, fast=false, horizontal=True)
NameError: name 'false' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.99.4.467
Mushrooms 0.0
